//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HutechMart.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HutechMartDbContext : DbContext
    {
        public HutechMartDbContext()
            : base("name=HutechMartDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_ChucVu> tbl_ChucVu { get; set; }
        public virtual DbSet<tbl_CuaHang> tbl_CuaHang { get; set; }
        public virtual DbSet<tbl_DangNhap> tbl_DangNhap { get; set; }
        public virtual DbSet<tbl_DoiTacGiaoHang> tbl_DoiTacGiaoHang { get; set; }
        public virtual DbSet<tbl_DonViTinh> tbl_DonViTinh { get; set; }
        public virtual DbSet<tbl_HoaDon> tbl_HoaDon { get; set; }
        public virtual DbSet<tbl_HoaDon_SanPham> tbl_HoaDon_SanPham { get; set; }
        public virtual DbSet<tbl_KhachHang> tbl_KhachHang { get; set; }
        public virtual DbSet<tbl_KhoHang> tbl_KhoHang { get; set; }
        public virtual DbSet<tbl_KhuyenMai> tbl_KhuyenMai { get; set; }
        public virtual DbSet<tbl_NhaCungCap> tbl_NhaCungCap { get; set; }
        public virtual DbSet<tbl_NhanVien> tbl_NhanVien { get; set; }
        public virtual DbSet<tbl_PhanLoai_GiaoHang> tbl_PhanLoai_GiaoHang { get; set; }
        public virtual DbSet<tbl_PhanLoai_KhachHang> tbl_PhanLoai_KhachHang { get; set; }
        public virtual DbSet<tbl_PhanLoai_NhaCungCap> tbl_PhanLoai_NhaCungCap { get; set; }
        public virtual DbSet<tbl_PhanLoai_SanPham> tbl_PhanLoai_SanPham { get; set; }
        public virtual DbSet<tbl_PhieuNhap> tbl_PhieuNhap { get; set; }
        public virtual DbSet<tbl_PhieuNhap_SanPham> tbl_PhieuNhap_SanPham { get; set; }
        public virtual DbSet<tbl_Phuong> tbl_Phuong { get; set; }
        public virtual DbSet<tbl_PhuongThucThanhToan> tbl_PhuongThucThanhToan { get; set; }
        public virtual DbSet<tbl_Quan> tbl_Quan { get; set; }
        public virtual DbSet<tbl_SanPham> tbl_SanPham { get; set; }
        public virtual DbSet<tbl_ThongKe> tbl_ThongKe { get; set; }
        public virtual DbSet<tbl_ThongKe_SanPham> tbl_ThongKe_SanPham { get; set; }
        public virtual DbSet<tbl_Tinh> tbl_Tinh { get; set; }
        public virtual DbSet<tbl_VAT> tbl_VAT { get; set; }
        public virtual DbSet<tbl_Voucher> tbl_Voucher { get; set; }
        public virtual DbSet<tbl_XuatXu> tbl_XuatXu { get; set; }
    }
}
