//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HutechMart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PhieuNhap_SanPham
    {
        public int id { get; set; }
        public Nullable<int> id_phieunhap { get; set; }
        public Nullable<int> id_sanpham { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<double> gianhap { get; set; }
        public Nullable<double> thanhtien { get; set; }
    
        public virtual tbl_PhieuNhap tbl_PhieuNhap { get; set; }
        public virtual tbl_SanPham tbl_SanPham { get; set; }
    }
}
