//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HutechMart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ThongKe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ThongKe()
        {
            this.tbl_ThongKe_SanPham = new HashSet<tbl_ThongKe_SanPham>();
        }
    
        public int id { get; set; }
        public string mathongke { get; set; }
        public string id_cuahang { get; set; }
        public Nullable<int> id_nhanvien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ThongKe_SanPham> tbl_ThongKe_SanPham { get; set; }
    }
}
