//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HutechMart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NhanVien
    {
        public int id { get; set; }
        public string manhanvien { get; set; }
        public Nullable<int> id_cuahang { get; set; }
        public Nullable<int> id_chucvu { get; set; }
        public string diachi_tentinh { get; set; }
        public string diachi_tenquan { get; set; }
        public string diachi_tenphuong { get; set; }
        public string diachi_sonha { get; set; }
        public string tennhanvien { get; set; }
        public string hinhanh { get; set; }
        public string gioitinh { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string sodienthoai { get; set; }
        public string sochungminh { get; set; }
        public string email { get; set; }
        public string facebook { get; set; }
        public Nullable<int> id_nguoitao { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<int> id_nguoicapnhat { get; set; }
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
        public string ghichu { get; set; }
        public Nullable<bool> tinhtrang { get; set; }
    
        public virtual tbl_ChucVu tbl_ChucVu { get; set; }
        public virtual tbl_CuaHang tbl_CuaHang { get; set; }
        public virtual tbl_DangNhap tbl_DangNhap { get; set; }
    }
}
