//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HutechMart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DangNhap
    {
        public int id_nhanvien { get; set; }
        public string taikhoan { get; set; }
        public string matkhau { get; set; }
        public Nullable<bool> loaitaikhoan { get; set; }
    
        public virtual tbl_NhanVien tbl_NhanVien { get; set; }
    }
}
