//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HutechMart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PhieuNhap
    {
        public int id { get; set; }
        public string maphieunhap { get; set; }
        public Nullable<int> id_nhacungcap { get; set; }
        public Nullable<int> id_nhanvien { get; set; }
        public Nullable<int> id_doitacgiaohang { get; set; }
        public Nullable<int> tongsoluong { get; set; }
        public Nullable<double> tongtien { get; set; }
        public DateTime ngaylap { get; set; }
        public string ghichu { get; set; }
        public Nullable<bool> tinhtrang { get; set; }
    
        public virtual tbl_DoiTacGiaoHang tbl_DoiTacGiaoHang { get; set; }
        public virtual tbl_NhaCungCap tbl_NhaCungCap { get; set; }
        public virtual tbl_PhieuNhap_SanPham tbl_PhieuNhap_SanPham { get; set; }
    }
}
