//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HutechMart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_KhachHang()
        {
            this.tbl_HoaDon = new HashSet<tbl_HoaDon>();
        }
    
        public int id { get; set; }
        public string makhachhang { get; set; }
        public Nullable<int> id_cuahang { get; set; }
        public Nullable<int> id_phanloai { get; set; }
        public string diachi_tentinh { get; set; }
        public string diachi_tenquan { get; set; }
        public string diachi_tenphuong { get; set; }
        public string diachi_sonha { get; set; }
        public string tenkhachhang { get; set; }
        public string gioitinh { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string sodienthoai { get; set; }
        public string sochungminh { get; set; }
        public string email { get; set; }
        public string facebook { get; set; }
        public Nullable<int> id_nguoitao { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<int> id_nguoicapnhat { get; set; }
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
        public string ghichu { get; set; }
        public Nullable<bool> tinhtrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_HoaDon> tbl_HoaDon { get; set; }
        public virtual tbl_PhanLoai_KhachHang tbl_PhanLoai_KhachHang { get; set; }
    }
}
