//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HutechMart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_HoaDon()
        {
            this.tbl_HoaDon_SanPham = new HashSet<tbl_HoaDon_SanPham>();
        }
    
        public int id { get; set; }
        public string mahoadon { get; set; }
        public Nullable<int> id_khachhang { get; set; }
        public Nullable<int> id_cuahanng { get; set; }
        public Nullable<int> id_nhanvien { get; set; }
        public Nullable<int> id_thanhtoan { get; set; }
        public Nullable<int> id_voucher { get; set; }
        public Nullable<int> id_vat { get; set; }
        public Nullable<int> tongsoluong { get; set; }
        public Nullable<double> tongtien { get; set; }
        public DateTime ngaylap { get; set; }
        public string ghichu { get; set; }
        public Nullable<bool> tinhtrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_HoaDon_SanPham> tbl_HoaDon_SanPham { get; set; }
        public virtual tbl_KhachHang tbl_KhachHang { get; set; }
        public virtual tbl_PhuongThucThanhToan tbl_PhuongThucThanhToan { get; set; }
    }
}
